name    'puppet-ipam'
version '0.0.3'
project_page 'https://github.com/ppouliot/puppet-ipam'
source 'https://github.com/ppouliot/puppet-ipam'
author 'Peter J. Pouliot'
license 'Apache License, Version 2.0'
summary 'A module for configuring and controlling IP Network Services'
description 'A module for configuring and controlling IP Network Services'
dependency 'ajjahn/dns', '>=2.0.2'
dependency 'puppetlabs/apt', '>='v2.2.2'
dependency 'puppetlabs-concat', 'v1.2.5'
dependency 'puppetlabs-dhcp', 'v0.4.0'
dependency 'puppetlabs-firewall', 'v1.8.1'
dependency 'puppetlabs-inifile', 'v1.5.0'
dependency 'puppetlabs-ntp', 'v4.2.0'
dependency 'puppetlabs-stdlib', 'v4.12.0'
